### ISSUE TITLE
Random number for games should round up to ceiling, not to floor

### ISSUE THREAD

**Issue by gyroscopico** [ebabel-eu/ebabel-library#7]
It's unlikely that we'll need to generate random numbers in a range that excludes the max value. Instead, the minimum value 0 is more suitable to be considered unneeded.
An example of this (and following the author's test case) is the dice with 6 faces.

Assuming that said, the method `randomNumber(max, min)` will usually force developers to do some algebra that the program could abstract already and so, for the dice, instead of `randomNumber(7,1)`, which feels somehow unnatural, we would rather write `randomNumber(6)`.

This case works also for cards or picking from any group of objects were 0 is usually not an option. These situations are the most usual for games.

**Comment by ebabel-eu** [comment]
Thanks for raising that issue and solving it in your pull request - all merged and published!
